### ISSUE TITLE
two lock queue 存在 datarace

### ISSUE THREAD

**Issue by gyr666** [smallnest/queue#1]
```
	q:=queue.NewCQueue()
	var wg sync.WaitGroup
	wg.Add(2)
	go func(){
		defer wg.Done()
		for i:=0;i<100000;i++{
			q.Enqueue(1)
		}
	}()
	go func(){
		defer wg.Done()
		for i:=0;i<100000;i++{
			_=q.Dequeue()
		}
	}()
	wg.Wait()
```
可以用 go run -race 复现一下

**Comment by smallnest** [comment]
谢谢，有趣的测试。这可以看作是可忽略的`data race`。

我专门写了一篇文章介绍这个case https://colobu.com/2020/09/07/go-race-detector-false-positive/

或者你参看https://stackoverflow.com/questions/37369031/two-lock-concurrent-queue-algorithm-issue
