### ISSUE TITLE
function Comment not correct when change to generic type 

### ISSUE THREAD

**Issue by bighunter513** [smallnest/queue#2]
In lockfree_queue.go 

// Dequeue removes and returns the value at the head of the queue.
// It returns nil if the queue is empty.
func (q *LKQueue[T]) Dequeue() T {

Actually , Here will never return nil unless T is some kind of pointer or interface;
basic type will return default value for T, like 0 for int , "" for string.

**Comment by smallnest** [comment]
yes, It return zero value for the type
